version: '3.1'
services:
 
 away:
  restart: always
  build: .
  command: python -u awaybot-trust-friends.py
  environment:
   - PYTHONUNBUFFERED=0
  volumes:
   - ./credentials.py:/app/mycredentials.py
  extra_hosts:
   - "steemd.steemit.com:34.225.141.27"

 amqp:
  restart: always
  build: .
  command: python amqp.py
  environment:
   - RABBITMQ_HOSTNAME=rabbitmq
   - RABBITMQ_EXCHANGE=steemit
  extra_hosts:
   - "rabbitmq:172.20.0.5"
  volumes:
   - ./credentials.py:/app/mycredentials.py
